github:
  branch: master
  repository: https://github.com/jjdepaul/sw-concourse-training.git
  username: jjdepaul
jobs:
- name: job-upload-release
  plan:
  - get: source-code
    params:
      depth: 1
  - get: cert-file
  - config:
      image_resource:
        source:
          repository: starkandwayne/concourse
        type: docker-image
      inputs:
      - name: source-code
      - name: cert-file
      platform: linux
      run:
        path: source-code/nginx_release/ci/tasks/upload-release.sh
    task: upload-release
  public: true
meta:
  name: jjdepaul-nginx-demo
  pipeline: jjdepaul-nginx-demo
  target: training
  url: https://pipes.starkandwayne.com
resources:
- name: source-code
  source:
    branch: master
    uri: https://github.com/jjdepaul/sw-concourse-training.git
  type: git
- name: cert-file
  source:
    filename: training-bosh.pem
    url: https://s3.us-east-2.amazonaws.com/dg-training-concourse/training-bosh.pem
    type: file-url

