github:
  branch: master
  repository: https://github.com/jjdepaul/sw-concourse-training.git
  username: jjdepaul
instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: nginx
    release: nginx
  name: nginx
  networks:
  - name: default
  stemcell: default
  vm_type: small
meta:
  name: jjdepaul-nginx-demo
  pipeline: jjdepaul-nginx-demo
  target: training
  url: https://pipes.starkandwayne.com
name: jjdepaul-nginx
release:
  name: jjdepaul-nginx
releases:
- name: nginx
  version: latest
stemcells:
- alias: default
  os: ubuntu-trusty
  version: 3586.46
update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 10
  update_watch_time: 1000-30000

